july16_django/customer/urls.py
from django.urls import path
from .views import *
app_name = 'customer'

urlpatterns = [
    path('', customer, name='customer'),
    path('customerlist', customerlist, name='customerlist'),
    path('edit/<int:id>/', edit_customer, name='edit_customer'),
    path('profile/<int:id>/', profile, name='profile'),
    path('delete/<int:id>/', delete, name='delete'),
]

july16_django/july16_django/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('manager/',include('manager.urls')),
    path('customer/',include('customer.urls')),
    path('main/',include('main.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

july16_django/main/urls.py
from django.urls import path
from .views import *
app_name = 'main'

urlpatterns = [
    path('', create, name='create'),

]

july16_django/manager/urls.py
from django.urls import path
from .views import *
app_name = 'manager'

urlpatterns = [
    path('', manager, name='manager'),
    path('managerlist', managerlist, name='managerlist'),
    path('edit/<int:id>/', edit_manager, name='edit_manager'),
    path('profile/<int:id>/', profile, name='profile'),
    path('delete/<int:id>/', delete, name='delete'),
    path('room/', room, name='room'),

]

july16_django/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home Page{% endblock %}</title>
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
     integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <style>
        * {
          box-sizing: border-box;
        }
        
        body {
          font-family: Georgia, 'Times New Roman', Times, serif;
          font-size: 18px;
        }
        
        .container {
          position: relative;
          max-width: 100%;
          margin: 0 auto;
        }
        
        .container img {vertical-align: middle;}
        
        .container .content {
          position: absolute;
          top: 0;
          background: rgba(110, 82, 63, 0.01); 
          color: #f1f1f1;
          width: 100%;
          padding: 20px;
          text-align: center;
          font-size: 20px;
          color: rgb(255, 255, 255);
        }

        .btn {
            background-color: rgba(51, 53, 51, 0.9);
            border: none;
            color: white;
            padding: 12px 16px;
            font-size: 16px;
            cursor: pointer;
            }
        .btn:hover {
            background-color: rgb(14, 109, 14);
        }
        .form-control {
          border-radius: 10px;
          border: thin solid lightgray;
        }
       
        </style>
      
</head>
<body>
    <div style="background-color: rgba(168, 167, 167, 0.65);">    
        <a href="{% url 'home' %}"><button class="btn"><i class="fa fa-home"></i> Home</button></a>&nbsp;&nbsp;
        <a href="{% url 'manager:manager' %}"><button class="btn"><i class="fas fa-tasks"></i> Manager</button></a>&nbsp;&nbsp;
        <a href="{% url 'customer:customer' %}"><button class="btn"><i class="fas fa-user-plus"></i> Customer</button></a>&nbsp;&nbsp;
        <a href="{% url 'main:create' %}"><button class="btn"><i class="fas fa-plus"></i> Signup</button></a>&nbsp;&nbsp;
    </div> 
    <div class="container">
        {% block bgimage %}<img src="{% static 'images/managerial.jpg' %}" alt="manage" style="width:100%;">{% endblock %}
        <div class="content">
          {% block heading %}<h1>Home Page</h1>{% endblock %}
          {% block list %}<br><br>
          <a href="{% url 'manager:manager' %}"><button class="btn"><i class="fas fa-tasks"></i> Manager</button></a>&nbsp;&nbsp;<br><br>
          <a href="{% url 'customer:customer' %}"><button class="btn"><i class="fas fa-user-plus"></i> Customer</button></a>&nbsp;&nbsp;  
         
          {% endblock %}
          {% block content1 %}  {% endblock %}
        </div> 
    </div>
    {% block content2 %}  {% endblock %}
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
</body>
</html>

july16_django/templates/room.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Room List</title>
</head>

<body>
    <center class='text-success'>
        <h1> Rooms list </h1>
    </center>
    <a class='link' href="{% url 'manager:manager' %}"><i class="fas fa-arrow-circle-left"></i>Back</a>
    

    <table class="table table-striped table-hover table-condensed table-bordered table-info">
        <thead>
            <tr>
                <th scope="col">SL.NO.</th>
               
                <th scope="col">Photos</th>
                <th scope="col">Room Type</th>
                <th scope="col">Price</th>
                <th scope="col">Capacity</th>
                <th scope="col">Contact no</th>
            </tr>
        </thead>
        <tbody>

            {% for mg in room_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>
                    {% if mg.image %}

                       <a href="{{mg.image.url}}"> <img src='{{mg.image.url}}' height=100 width=250></a>
                        {% else %}
                            No Image Found
                        {% endif %}
                </td>
                <td>{{mg.room_type}}</td>
                <td>{{mg.price}}</td>
                <td>{{mg.capacity}}</td>
                <td>{{mg.contactno}}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>